### ISSUE TITLE
Source code for NuGet Pakage ver 104

### ISSUE THREAD

**Issue by SergeySWork** [bubibubi/sqliteef6migrations#1]
Hello, @bubibubi !
Thank you so much for your work!
I am trying to use Nuget ver 1.0.104 for migrations. I have existing EF6 SQL migrations and trying to adopt them to SQLite. I have Issue when creating indexes in tables for Columns with the same name. I hoped I can change the source code to use Table Name in Index Name. But GitHub and Codeplex seems to have the source code for 102 version.
Could you help me please with this issue? 
I will be happy to make a pull request with my changes.

Could you please clarify licence of this project?

**Comment by bubibubi** [comment]
Hi Sergey,
I've just commited the version I'm using now.
Please, if you fix something, send the updates so we can keep the library working!

About the license, actually it's MIT license.
