### ISSUE TITLE
Duplicate index name generated

### ISSUE THREAD

**Issue by lexluthor91** [bubibubi/sqliteef6migrations#6]
When I have a class that has two related collections, like so:

```
    public class Plant
    {
        public long Id { get; set; }

        public ICollection<Aggregate> Aggregates { get; set; }
        public ICollection<Spillway> Spillways { get; set; }
    }
```

It tries to create two indices with the same name, which fails like this:

```
 CREATE INDEX "IX_Plant_Id" ON "Aggregates" ("Plant_Id")
-- Executing at 3/20/2018 9:16:13 AM +01:00
-- Completed in 0 ms with result: 0

 CREATE INDEX "IX_Plant_Id" ON "Spillways" ("Plant_Id")
-- Executing at 3/20/2018 9:16:13 AM +01:00
-- Failed in 0 ms with error: SQL logic error
index IX_Plant_Id already exists

Exception thrown: 'System.Data.SQLite.SQLiteException' in EntityFramework.dll
An exception of type 'System.Data.SQLite.SQLiteException' occurred in EntityFramework.dll but was not handled in user code
SQL logic error
index IX_Plant_Id already exists
```

I guess adding a timestamp to the name to make it unique would fix the issue? Is there a workaround this, or do we have to wait for a new release?

**Comment by steuic** [comment]
Hi,
I encountered the same issue reported from thlexluthor91: is there any new release planned to fix the issue? 
Thanks!

**Comment by bubibubi** [comment]
I'm actually working on another project but I will fix it as soon as I can.

**Comment by steuic** [comment]
Thanks!

**Comment by bubibubi** [comment]
@steuic Thanks for the commit! I've aligned the fixes to other EF providers otherwise the fixes are perfect!!! THANKS!!!
