### ISSUE TITLE
Unable to extend SQLiteMigrationSqlGenerator

### ISSUE THREAD

**Issue by pippolino** [bubibubi/sqliteef6migrations#9]
The SQLiteMigrationSqlGenerator is sealed class and cannot extend. It's possible remove sealed ?

**Comment by bubibubi** [comment]
I think so. If the extensions are related to EF you could work on the base class. If you make some fixes or enhancements I will include them in master.

**Comment by pippolino** [comment]
Hi @bubibubi, I understand, but also Microsoft has made the class extendable [SqlServerMigrationSqlGenerator](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlservermigrationsqlgenerator?view=entity-framework-6.2.0). The changes that do not concern the EF can not be put on the master but are customization of a project.

**Comment by bubibubi** [comment]
@pippolino you can download the new version that includes this fixes from NuGet.
Greetings from Bologna!

**Comment by pippolino** [comment]
Thanks ... Same version 1.0.104 or 1.0.105 ?

**Comment by bubibubi** [comment]
105

**Comment by pippolino** [comment]
I do not see that version on [nuget](https://www.nuget.org/packages/System.Data.SQLite.EF6.Migrations/)

**Comment by bubibubi** [comment]
Ops... Probably something went wrong during compile...

**Comment by bubibubi** [comment]
Now you should find it. It was a wrong nuget version.

**Comment by pippolino** [comment]
> Now you should find it. It was a wrong nuget version.

Thanks!!!!

Greetings from Florence!
